### PR TITLE
added 18-instagram

### LINKED ISSUE #89: Adding Instagram Login Page
**Is your feature request related to a problem? Please describe.**
I want to add Instagram Login Template. This page is built using plain HTML and CSS.

**Describe the solution you'd like**
Make a clone of Instagram login page

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by AbhJ**
Closes 

## Description
Added Instagram Login Template. This page is built using plain HTML and CSS.

## Issue Reference
Closes #89

## Screenshoot

18-instagram

## Todos

- [x] Add screenshots on `screenshoots` directory
- [x] Update the list in `readme.md`
- [x] Add in `src/index.html`
- [x] Change the author text and link

## Minimum Support

- [x] Click 🌟 button to this repo
- [x] Follow the Author

## Consider to Support

- 👉 🇮🇩 [Trakteer](https://trakteer.id/mazipan?utm_source=github)
- 👉 🌍 [BuyMeACoffe](https://www.buymeacoffee.com/mazipan?utm_source=github)
- 👉 🌍 [Paypal](https://www.paypal.me/mazipan?utm_source=github)
- 👉 🌍 [Ko-Fi](https://ko-fi.com/mazipan)

### CODE REVIEW

**Comment by AbhJ** [comment]
@mazipan Please review this instagram login page when you are free. Thank you.

**Comment by AbhJ** [comment]
Hi @mazipan I have made the changes. Please check. Thanks.

**Comment by mazipan** [comment]
Some comments still not resolved

**Comment by AbhJ** [comment]
Hi, I have resolved the comments. Please check. Thanks.

**Comment by mazipan** [comment]
All good, can you try to run `yarn run lint --fix` from your local.
And check if there is any linter problem in your local

**Pull request merged**
