### PR TITLE
Quora indo

### PR DESCRIPTION
**Pull request by naufaldi**
Developer: `@naufaldi`
Description: Adding Login Page Quora Indo, There are two version. Mobile & Dekstop, bcs its different , adding two of them. 
Design Source: if available

## Screenshoots

Attach screenshoots if necessary, attach the before and the after if it's a bug fixing.
If it's new design, please attach for mobile and desktop screenshoots.

## TODOS

- [ done ] Add screenshots on `screenshoots` directory (if new design)
- [ done ] Update the list in `readme.md` (if new design)
- [done ] Add in `src/index.html` (if new design)
- [done ] Change the author text and link (if new design)

@mazipan please review

// If it's a bugfix, please mention the slicer on `readme.md`.

### CODE REVIEW

**Comment by naufaldi** [comment]
also, pls add label "hacktoberfest" for counting as PR 😂

**Comment by mazipan** [comment]
Conflict nih, please fix the conflict ya

**Comment by naufaldi** [comment]
sudah mas @mazipan

**Review by mazipan — APPROVED** [review]

**Comment by mazipan** [comment]
@all-contributors please add @naufaldi for code

**Pull request merged**
