### PR TITLE
Added Netflix Login Template

### LINKED ISSUE #77: [design] - Netflix
**Is your feature request related to a problem? Please describe.**
Netflix is one of the popular websites. Thus its login page needs to be added.

**Describe the solution you'd like**
Make a clone of [Netflix](https://www.netflix.com/in/login) login page

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by SubhamKarmakar24**
### Description:

Added Netflix Login Template. This page is built using plain HTML and CSS.

### Issue Reference

Closes #77 

### Screenshot
Untitled

### Todos

- [X] Add screenshots on `screenshoots` directory
- [X] Update the list in `readme.md`
- [X] Add in `src/index.html`
- [X] Change the author text and link

### Minimum Support

- [X] Click 🌟 button to this repo
- [X] Follow the Author

### Consider to Support

- 👉 🇮🇩 [Trakteer](https://trakteer.id/mazipan?utm_source=github)
- 👉 🌍 [BuyMeACoffe](https://www.buymeacoffee.com/mazipan?utm_source=github)
- 👉 🌍 [Paypal](https://www.paypal.me/mazipan?utm_source=github)
- 👉 🌍 [Ko-Fi](https://ko-fi.com/mazipan)

### CODE REVIEW

**Comment by SubhamKarmakar24** [comment]
@mazipan Can you please review the changes?
If everything is okay, could you please add hacktoberfest-accepted label to the PR or merge the PR.
I have done all the To-Dos for the PR.
Thanks.

**Review by mazipan — APPROVED** [review]
Looks good

**Comment by mazipan** [comment]
The build is blocked by the failed CI

Related w https://github.com/parcel-bundler/parcel/issues/5943

**Comment by SubhamKarmakar24** [comment]
> 
> 
> The build is blocked by the failed CI
> 
> Related w [parcel-bundler/parcel#5943](https://github.com/parcel-bundler/parcel/issues/5943)

@mazipan 
Can you please tell me what might be the reason this is getting blocked? I will do the necessary changes.

**Comment by SubhamKarmakar24** [comment]
@mazipan Can you check now if everything is working fine or not?

**Comment by mazipan** [comment]
I still need to find a time to check why the CI is failed

**Comment by SubhamKarmakar24** [comment]
> 
> 
> I still need to find a time to check why the CI is failed.
> 
> I plan to upgrade the Parcel version.

Sure. Thanks!

**Comment by mazipan** [comment]
But I can merge this first, and fix the CI later.
But expect your changes will not reflect on the production

**Comment by SubhamKarmakar24** [comment]
> 
> 
> But I can merge this first, and fix the CI later. But expect your changes will not reflect on the production

Yeah, I dont think it will affect production. I only added html, css and few images.

**Comment by SubhamKarmakar24** [comment]
> 
> 
> But I can merge this first, and fix the CI later. But expect your changes will not reflect on the production

I checked the Check Build UI error that was generated from the CI.
Untitled
Its showing error is in `src/04-kitabisa/index.html`
I have not changed any thing in this file. Maybe the error is due to Percel

**Pull request merged**
